# Generated by Django 5.0.6 on 2024-07-08 06:43

import datetime
import django.db.models.deletion
import django_admin_geomap
import geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("macaddress", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=100)),
                (
                    "w3w_location",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("geolocation", geoposition.fields.GeopositionField(max_length=42)),
                ("is_active", models.BooleanField(default=False)),
                ("deployed_at", models.DateTimeField(null=True)),
                ("last_seen", models.DateTimeField(null=True)),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name="MetricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement", models.FloatField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 8, 6, 43, 46, 735435)
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
                (
                    "measurement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.metrictype",
                    ),
                ),
            ],
        ),
    ]
