# Generated by Django 5.0.6 on 2024-07-08 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemetric",
            name="recorded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 8, 6, 44, 44, 815482, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
