# Generated by Django 5.0.6 on 2024-07-08 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_devicemetric_recorded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemetric",
            name="recorded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 8, 7, 6, 1, 936698, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
