# Generated by Django 5.0.6 on 2024-07-08 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_devicemetric_recorded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ttn_dev_eui",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="devicemetric",
            name="recorded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 8, 7, 32, 58, 859928, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
