# Generated by Django 5.0.6 on 2024-07-08 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_ttn_dev_eui_alter_devicemetric_recorded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemetric",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
